# Generated by Django 5.0.2 on 2024-04-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_wardmodel_options_bedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedmodel',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='department.wardmodel', verbose_name='Находится в палате'),
        ),
    ]
