# Generated by Django 5.0.2 on 2024-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_bedmodel_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='slug',
            field=models.SlugField(default='salaf', editable=False, verbose_name='Слаг'),
        ),
    ]
