# Generated by Django 5.0.2 on 2024-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_departmentmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
