# Generated by Django 5.0.2 on 2024-04-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_departmentmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='department.departmentmodel', verbose_name='Находится в отделении'),
        ),
    ]
