# Generated by Django 5.0.2 on 2024-04-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_wardmodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
