# Generated by Django 5.0.2 on 2024-04-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_bedmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedmodel',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
