# Generated by Django 5.0.2 on 2024-04-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_wardmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardmodel',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
