# Generated by Django 5.0.2 on 2024-04-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_occupyward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OccupyWard',
        ),
    ]
