# Generated by Django 5.0.2 on 2024-04-14 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_departmentmodel_slug'),
        ('patients', '0004_delete_occupyward'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupyWardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkin', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата заселения')),
                ('date_checkout', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата выселения')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.bedmodel', verbose_name='Койка')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmodel', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Заселенная койка',
                'verbose_name_plural': 'Заселенные койки',
            },
        ),
    ]
