# Generated by Django 5.0.2 on 2024-04-17 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_occupywardmodel_date_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupywardmodel',
            name='date_checkout',
            field=models.DateField(default=datetime.date(2024, 4, 20), null=True, verbose_name='Дата выселения'),
        ),
    ]
