# Generated by Django 5.0.2 on 2024-04-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_occupywardmodel_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientModel',
        ),
    ]
